### PR TITLE
Ruby 3 support

### PR DESCRIPTION
**Pull request by hasghari**

### CODE REVIEW

**Comment by hasghari** [comment]
GitHub status checks are not showing the Travis build but you can see them here: https://www.travis-ci.com/github/hasghari/capybara_error_intel

**Comment by dillonhafer** [comment]
This would help me out, any chance this could get merged?

**Comment by dkarter** [comment]
Thanks @hasghari !

**Comment by dkarter** [comment]
@dillonhafer published as v2.0.0
https://github.com/dkarter/capybara_error_intel/releases/tag/v2.0.0

**Comment by dillonhafer** [comment]
❤️

**Pull request merged**
